include(CheckCCompilerFlag)
include(CheckCXXCompilerFlag)

# GCC has some bugs on uninitialized detection.
if (NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU")
  message("Adding -Wuninitialized, compiler ${CMAKE_CXX_COMPILER_ID}")
  #list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmaybe-uninitialized")
  list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wuninitialized")
endif()

list(APPEND C_COMPILER_FLAGS_TO_USE "-Wall")
list(APPEND C_COMPILER_FLAGS_TO_USE "-Wfatal-errors")
list(APPEND C_COMPILER_FLAGS_TO_USE "-Wextra")
list(APPEND C_COMPILER_FLAGS_TO_USE "-g")
list(APPEND C_COMPILER_FLAGS_TO_USE "-march=native")

if(build_type MATCHES "debug")
	list(APPEND C_COMPILER_FLAGS_TO_USE "-O0")
elseif(build_type MATCHES "release")
	# Enable debugging symbols in Release mode to have detailed information in both Instruments (for AppleClang) and Boost Stacktraces (for Linux)
endif()

foreach (FLAG IN LISTS C_COMPILER_FLAGS_TO_USE)
	# Check if the compiler supports the flag. The result of this test
	# is printed to STDOUT when calling `cmake`.
	string(REGEX REPLACE "[-=+]" "" FLAG_NO_SIGNS ${FLAG})
	check_c_compiler_flag(${FLAG} C_COMPILER_SUPPORTS_${FLAG_NO_SIGNS})
	if(C_COMPILER_SUPPORTS_${FLAG_NO_SIGNS})
		# For some strange reason, add_compile_options() change the result of check_c_compiler_flag()!!! So don't use it until
		# https://gitlab.kitware.com/cmake/cmake/issues/19441
		# is clarified
		# add_compile_options($<$<COMPILE_LANGUAGE:C>:${FLAG}>)
		string(APPEND CMAKE_C_FLAGS " ${FLAG}")
	endif()
endforeach()

# Same as previous for the C++ compiler
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wall")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wfatal-errors")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wextra")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-g")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-fPIC")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-march=native")

# Exhaustive list of flags.
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Waddress")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Waggressive-loop-optimizations")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Waligned-new")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Walloc-zero")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Warith-conversion")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Warray-bounds")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wattributes")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wattribute-alias")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wbad-function-cast")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wbuiltin-macro-redefined")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wno-error=c++11-compat")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wc99-c11-compat")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wcast-align")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wcast-qual")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wc++-compat")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wchar-subscripts")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wclass-memaccess")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wclobbered")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wcomment")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wconditionally-supported")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wconversion-null")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wcoverage-mismatch")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wctor-dtor-privacy")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wcpp")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wctad-maybe-unsupported")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdangling-else")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdeclaration-after-statement")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdelete-non-virtual-dtor")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdeprecated")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdeprecated-declarations")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wno-error=deprecated-declarations")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdeprecated-copy")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdeprecated-enum-enum-conversion")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdeprecated-enum-float-conversion")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdisabled-optimization")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wdiv-by-zero")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wduplicated-branches")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wduplicated-cond")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Weffc++")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wempty-body")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wendif-labels")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wenum-compare")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wexcept")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wexcept-type")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wexpansion-to-defined")
# There are legitime uses of this, but we treat warnings as errors, so we disable the test.
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wfloat-equal")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wformat")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wformat-contains-nul")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wformat-extra-args")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wformat-nonliteral")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wformat-overflow")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wformat-security")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wformat-y2k")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wfree-nonheap-object")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wframe-address")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Whsa")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wif-not-aligned")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wignored-qualifiers")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wimplicit")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wimplicit-fallthrough")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wimplicit-function-declaration")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wimplicit-int")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wint-to-pointer-cast")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Winit-self")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Winvalid-offsetof")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Winvalid-pch")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wjump-misses-init")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wliteral-suffix")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wlogical-op")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wlong-long")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmain")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmismatched-tags")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmissing-braces")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmissing-field-initializers")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmissing-include-dirs")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmissing-prototypes")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmultiple-inheritance")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wnamespaces")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wnarrowing")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wnested-externs")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmudflap")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wmultichar")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wnon-template-friend")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wnon-virtual-dtor")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wnonnull")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wnull")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Woverflow")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpedantic-ms-format")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpmf-conversions")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpointer-to-int-cast")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpragmas")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wrestrict")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wreturn-local-addr")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wterminate")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-result")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wnull-dereference")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wold-style-cast")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wold-style-definition")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Woverlength-strings")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Woverride-init-side-effects")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpacked")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpacked-bitfield-compat")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpacked-not-aligned")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wparentheses")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpedantic-ms-format")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wplacement-new")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpointer-arith")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wpointer-compare")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wredundant-decls")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wregister")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wreorder")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wreturn-type")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wsequence-point")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wsign-compare")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wsign-conversion")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wsign-promo")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wsized-deallocation")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wsizeof-pointer-memaccess")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wstack-protector")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wstrict-aliasing")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wstrict-null-sentinel")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wstrict-overflow")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wstrict-prototypes")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wstringop-overflow")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wstringop-truncation")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wsubobject-linkage")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wswitch")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wswitch-bool")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wswitch-unreachable")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wsync-nand")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wtemplates")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wtraditional")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wtraditional-conversion")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wtrampolines")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wtrigraphs")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wtype-limits")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunknown-pragmas")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunsafe-loop-optimizations")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunsuffixed-float-constants")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-but-set-parameter")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-but-set-variable")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-function")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-label")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-local-typedefs")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-macros")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-parameter")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-value")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wunused-variable")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wvariadic-macros")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wno-error=vector-operation-performance")
#list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wvirtual-inheritance")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wvla")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wvolatile-register-var")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wwrite-strings")
if( (build_type MATCHES "debug") AND (CODE_COVERAGE) )
   message("Adding coverage flags")
   list(APPEND CXX_COMPILER_FLAGS_TO_USE "--coverage")
   list(APPEND CXX_COMPILER_FLAGS_TO_USE "-ftest-coverage")
   list(APPEND CXX_COMPILER_FLAGS_TO_USE "-fprofile-arcs")
   set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --coverage -ftest-coverage -fprofile-arcs" )
endif()

if(build_type MATCHES "debug")
	list(APPEND CXX_COMPILER_FLAGS_TO_USE "-O0")
elseif(build_type MATCHES "release")
	list(APPEND CXX_COMPILER_FLAGS_TO_USE "-ftree-vectorize")
	# Enable debugging symbols in Release mode to have detailed information in both Instruments (for AppleClang) and Boost Stacktraces (for Linux)
endif()

# Disable warnings here:
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wno-alloc-zero")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wno-maybe-uninitialized")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wno-pragmas")
list(APPEND CXX_COMPILER_FLAGS_TO_USE "-Wno-unknown-warning-option")

foreach (FLAG IN LISTS CXX_COMPILER_FLAGS_TO_USE)
	# Check if the compiler supports the flag. The result of this test
	# is printed to STDOUT when calling `cmake`.
	string(REGEX REPLACE "[-=+]" "" FLAG_NO_SIGNS ${FLAG})
	check_cxx_compiler_flag(${FLAG} CXX_COMPILER_SUPPORTS_${FLAG_NO_SIGNS})
	if(CXX_COMPILER_SUPPORTS_${FLAG_NO_SIGNS})
		# For some strange reason, add_compile_options() change the result of check_cxx_compiler_flag()!!! So don't use it until
		# https://gitlab.kitware.com/cmake/cmake/issues/19441
		# or
		# https://stackoverflow.com/questions/56856057/cmake-incorrectly-identifying-valid-c-compiler-options
		# are clarified
		# add_compile_options($<$<COMPILE_LANGUAGE:CXX>:${FLAG}>)
		string(APPEND CMAKE_CXX_FLAGS " ${FLAG}")
	endif()
endforeach()

# Remove hidden symbols from the resulting output
if(LINUX AND (NOT(CMAKE_CXX_COMPILER_ID MATCHES "Clang")) AND (NOT(CMAKE_CXX_COMPILER_ID MATCHES "Intel")))
	string(APPEND CMAKE_CXX_FLAGS " -Wl,--exclude-libs,ALL")
endif()
